### ISSUE TITLE
Level 2 and Level 3 Menu Items not working

### ISSUE THREAD

**Issue by sercosys** [lyrasoft/quickcontent#3]
I try to create a simple menu 3 levels deep:
Level1
      Level2.1
           Level3.1

Beispiel
   Sub1
          Sub2

In HTML:

<ul>
<li><strong>Level1</strong>
<ul>
<li><strong>Level2.1</strong>
<ul>
<li><strong>Level3.1</strong></li>
</ul>

</li>
</ul>
</li>
<li><strong>Beispiel</strong>

<ul>
<li><strong>Sub1</strong>
<ul>
<li><strong>Sub2</strong></li>
</ul>

</li>
</ul>
</li>
</ul>

Quickcontent just creates the first level but no sublevels! What's wrong?
I'm using Joomla 3.4.3

Thank you!!

Mike

**Comment by asika32764** [comment]
Did you make every list item **strong** style?

**Comment by sercosys** [comment]
Yes, i need a „single article“ for each menu item.

When i try this, it works but only for the first item:

 

·        First

o   sub1

o   sub2

§  subsub1

·        Second

o   sub1

o   sub2

§  subsub1

 

„Second“ (and it’s sub-items) was not created… L

So i have to split the Main-Menu:

 



 

How can i handle this? i have more Projects in the future with structures like that:

 

 

·       Anlage            

o   Driving Range/Übungsbereich        

o   öffentlicher 6-Loch-Platz    

o   27-Loch-Anlage        

§  Runde A

§  Runde B

§  Runde C

§  Vorgabentabellen

§  Fahnenpositionen

o   Platzübersicht           

o   Auszeichnungen        

§  Leading Golf Courses of Germany

§  Golf & Natur

§  Premium Golfschule

o   Geschichte    

 

 

·       Gäste 

o   Öffnungszeiten         

o   Platzbelegung           

o   Greenfee       

o   Hotelliste       

o   Anfahrt          

o   Mitglied werden        

o   Partnerclubs  

o   Information english   

o   Startzeiten

o   Archiv            

o   Mini-Club      

 

·       Mitglieder      

o   Präsidium       

o   Platzbelegung

o   Fitnessstudio 

o   Mini-Club      

o   Startzeiten

o   Partnerclubs  

o   Initiative        

o   Vorgabenabfrage      

o   Clubmagazin "Tee-Times" 

 

·       Sport  

o   Turnierkalender       

§  Turnieranmeldung

§  Startlisten

§  Turnierergebnisse

§  Spiel- & Wettspielordnung

o   BWGV Leistungsstützpunkt           

o   Jugendförderung      

§  AK 18 Jungen

§  AK 18 Mädchen

§  JMP

§  Jugendtraining

o   Spielkreise     

§  Damen

§  Herren

§  Senioren

o   Herrenmannschaft    

o   Damenmannschaft    

o   AK 35 Herren           

o   AK 35 Damen            

o   AK 50 Herren           

o   AK 50 Damen            

o   AK 65 Herren           

o   AK 65 Damen            

 

·       Über uns        

o   Präsidium       

o   Team Sekretariat     

o   Team Golfschule      

o   Team Greenkeeping 

o   Impressum     

o   Öffnungszeiten         

 

·       News  

o   News-Archiv 

o   Foto-Galerie 

o   Presse            

o   Downloads     

 

·       Golfschule     

o   Premium Golfschule 

o   Golf lernen    

o   Team Golfschule      

o   offenes Training       

o   Einsteigerkurse        

o   Platzreifekurse         

o   Kursanmeldung         

 

 

Thank you very much for your help!!!

 

Greets

Mike

 

 

M. Kühner 

- Geschäftsführer -

 

SERCOSYS

Altinger Str. 29

71126 Gäufelden

 

------------------------

Service-Hotline:

07032 / 37 48 14

------------------------

Mobil: 0172 / 7144028

Fax:  07032 / 95 70 40

 

E-Mail:  <mailto:info@sercosys.de> info@sercosys.de

Web:  <http://www.sercosys.de/> www.sercosys.de 

 

sercosys-logo-280

 

Umsatzsteuer-Identifikationsnummer gemäß §27a Umsatzsteuergesetz: DE239635968



Diese E-Mail könnte vertrauliche und/oder rechtlich geschützte Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist nicht gestattet. Wir weisen darauf hin, das über das Internet versandte und eingehende E-Mails leicht  verfälscht oder unter fremdem Namen erstellt werden können. Eine Haftung für die Unversehrtheit von E-Mails nach Verlassen unseres Hauses und für eventuelle Schäden durch einen Computervirenbefall wird ausgeschlossen. Dieser Haftungsausschluss gilt nur soweit gesetzlich zulässig.

 

Von: Simon Asika [mailto:notifications@github.com] 
Gesendet: Dienstag, 1. September 2015 03:56
An: asikart/quickcontent
Cc: sercosys
Betreff: Re: [quickcontent] Level 2 and Level 3 Menu Items not working (#3)

 

Did you make every list item strong style?

**Comment by asika32764** [comment]
The article should only at leaf node, you must use category to wrap all articles.

Then you can move article menu items to first level in menu manager.
